spring:
  application:
    name: task-management-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/task_management}
    username: ${DB_USERNAME:task_user}
    password: ${DB_PASSWORD:task_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: never

