package com.ejacot.taskmanagement.hotel;

import com.ejacot.taskmanagement.user.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.math.*;
import java.security.SecureRandom;
import java.time.*;
import java.util.*;

@Service @Transactional
public class AdminService {
 private final UserAccountRepository users;private final WorkTypeRepository types;private final PayRateRepository rates;private final WorkLogRepository logs;private final PasswordEncoder encoder;private final SecureRandom random=new SecureRandom();
 public AdminService(UserAccountRepository users,WorkTypeRepository types,PayRateRepository rates,WorkLogRepository logs,PasswordEncoder encoder){this.users=users;this.types=types;this.rates=rates;this.logs=logs;this.encoder=encoder;}
 @Transactional(readOnly=true) public AdminDtos.EmployeeList employees(String username){UserAccount actor=actor(username);return new AdminDtos.EmployeeList(users.findAllByHotelIdOrderByActiveDescUsernameAsc(hotel(actor)).stream().map(u->AdminDtos.EmployeeAdminView.from(u,inviteLink(u))).toList());}
 public AdminDtos.EmployeeAdminView createEmployee(String username,AdminDtos.EmployeeUpsert r){UserAccount actor=actor(username);String login=normalize(r.username());if(users.existsByUsername(login))throw new ResponseStatusException(HttpStatus.CONFLICT,"Username existent");UserRole role=allowedRole(actor,r.role());BigDecimal hourly=actor.getRole()==UserRole.EMPLOYER?r.hourlyRate():BigDecimal.ZERO;String password=r.temporaryPassword()==null||r.temporaryPassword().isBlank()?randomToken(10):r.temporaryPassword();UserAccount saved=users.save(new UserAccount(login,encoder.encode(password),blank(r.email()),blank(r.phone()),role,hourly,actor.getHotel()));saved.adminUpdate(login,blank(r.firstName()),blank(r.lastName()),blank(r.email()),blank(r.phone()),blank(r.address()),r.steuerClass(),role,hourly,actor.getHotel(),blank(r.teamName()));if(actor.getRole()==UserRole.EMPLOYER)rates.save(new PayRate(saved,hourly,LocalDate.now()));saved.invite(randomToken(32),Instant.now().plus(Duration.ofDays(14)));return AdminDtos.EmployeeAdminView.from(saved,inviteLink(saved));}
 public AdminDtos.EmployeeAdminView updateEmployee(String username,Long id,AdminDtos.EmployeeUpsert r){UserAccount actor=actor(username);UserAccount employee=employee(actor,id);String login=normalize(r.username());users.findByUsername(login).filter(u->!u.getId().equals(id)).ifPresent(u->{throw new ResponseStatusException(HttpStatus.CONFLICT,"Username existent");});if(actor.getRole()!=UserRole.EMPLOYER&&employee.getRole()==UserRole.EMPLOYER)throw new ResponseStatusException(HttpStatus.FORBIDDEN);UserRole role=allowedRole(actor,r.role());BigDecimal hourly=actor.getRole()==UserRole.EMPLOYER?r.hourlyRate():employee.getHourlyRate();employee.adminUpdate(login,blank(r.firstName()),blank(r.lastName()),blank(r.email()),blank(r.phone()),blank(r.address()),r.steuerClass(),role,hourly,actor.getHotel(),blank(r.teamName()));if(r.temporaryPassword()!=null&&!r.temporaryPassword().isBlank())employee.changePassword(encoder.encode(r.temporaryPassword()));if(actor.getRole()==UserRole.EMPLOYER)rates.save(new PayRate(employee,hourly,LocalDate.now()));return AdminDtos.EmployeeAdminView.from(employee,inviteLink(employee));}
 public AdminDtos.EmployeeAdminView setActive(String username,Long id,AdminDtos.ActiveRequest r){UserAccount actor=actor(username);UserAccount employee=employee(actor,id);if(actor.getId().equals(employee.getId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Nu îți poți dezactiva propriul cont");if(r.active())employee.activate();else employee.deactivate();return AdminDtos.EmployeeAdminView.from(employee,inviteLink(employee));}
 public AdminDtos.InvitationView invite(String username,Long id){UserAccount actor=actor(username);UserAccount employee=employee(actor,id);employee.invite(randomToken(32),Instant.now().plus(Duration.ofDays(14)));return new AdminDtos.InvitationView(employee.getId(),inviteLink(employee),employee.getInvitationExpiresAt());}
 @Transactional(readOnly=true) public AdminDtos.HotelSettings hotelSettings(String username){return AdminDtos.HotelSettings.from(actor(username).getHotel());}
 public AdminDtos.HotelSettings updateHotel(String username,AdminDtos.HotelSettings r){UserAccount actor=actor(username);if(actor.getRole()!=UserRole.EMPLOYER)throw new ResponseStatusException(HttpStatus.FORBIDDEN);actor.getHotel().updateSettings(r.name(),r.city(),r.normalRoomsPerHour(),r.juniorRoomsPerHour(),r.presidentRoomsPerHour(),r.sundayPremiumPercent(),r.nightPremiumPercent(),r.holidayPremiumPercent(),r.defaultBreakMinutes());return AdminDtos.HotelSettings.from(actor.getHotel());}
 public HotelDtos.WorkTypeView updateType(String username,Long id,AdminDtos.WorkTypeUpdate r){UserAccount actor=actor(username);WorkType type=types.findById(id).filter(t->t.getHotel().getId().equals(hotel(actor))).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));type.update(r.code().trim().toUpperCase(),r.name().trim(),r.unit(),r.roomsPerHour(),r.color()==null?"#246F60":r.color(),r.active(),r.defaultStartTime(),r.defaultEndTime(),r.defaultBreakMinutes());return HotelDtos.WorkTypeView.from(type);}
 @Transactional(readOnly=true) public AdminDtos.MonthlyClose monthlyClose(String username,int year,int month){UserAccount actor=actor(username);if(actor.getRole()!=UserRole.EMPLOYER)throw new ResponseStatusException(HttpStatus.FORBIDDEN);LocalDate from=LocalDate.of(year,month,1),to=from.withDayOfMonth(from.lengthOfMonth());List<WorkLog> approved=logs.findAllByHotelIdAndStatusOrderByWorkDateDesc(hotel(actor),LogStatus.APPROVED).stream().filter(l->!l.getWorkDate().isBefore(from)&&!l.getWorkDate().isAfter(to)).toList();BigDecimal hours=approved.stream().map(WorkLog::getCalculatedHours).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal gross=approved.stream().map(l->l.getCalculatedHours().multiply(rate(l.getEmployee(),l.getWorkDate()))).reduce(BigDecimal.ZERO,BigDecimal::add).setScale(2,RoundingMode.HALF_UP);return new AdminDtos.MonthlyClose(year,month,hours,gross,gross.multiply(new BigDecimal("0.70")).setScale(2,RoundingMode.HALF_UP),approved.size());}
 private BigDecimal rate(UserAccount employee,LocalDate date){return rates.findFirstByEmployeeUsernameAndEffectiveFromLessThanEqualOrderByEffectiveFromDesc(employee.getUsername(),date).map(PayRate::getHourlyRate).orElse(employee.getHourlyRate());}
 private UserAccount actor(String username){UserAccount actor=users.findByUsername(username).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED));if(actor.getHotel()==null)throw new ResponseStatusException(HttpStatus.CONFLICT);return actor;}
 private UserAccount employee(UserAccount actor,Long id){return users.findById(id).filter(u->u.getHotel()!=null&&u.getHotel().getId().equals(hotel(actor))).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private Long hotel(UserAccount u){return u.getHotel().getId();}
 private String normalize(String value){return value.trim().toLowerCase();}
 private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
 private String randomToken(int length){String alphabet="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";StringBuilder out=new StringBuilder();for(int i=0;i<length;i++)out.append(alphabet.charAt(random.nextInt(alphabet.length())));return out.toString();}
 private String inviteLink(UserAccount u){return u.getInvitationToken()==null?null:"/index.html?invite="+u.getInvitationToken();}
 private UserRole allowedRole(UserAccount actor,UserRole requested){if(actor.getRole()==UserRole.EMPLOYER)return requested;if(requested==UserRole.EMPLOYER||requested==UserRole.MANAGER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Doar angajatorul poate seta roluri administrative");return requested;}
}
