package com.ejacot.taskmanagement.hotel;

import com.ejacot.taskmanagement.user.*;
import org.springframework.http.HttpStatus;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.math.*;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;

@Service @Transactional
public class EmployeePortalService {
 private final UserAccountRepository users;private final EmployeeRequestRepository requests;private final WorkLogRepository logs;private final PayRateRepository rates;private final NotificationRepository notifications;private final PasswordEncoder encoder;private final ShiftPlanRepository plans;private final PlanLogService planLogs;private final RoomAssignmentRepository roomAssignments;
 public EmployeePortalService(UserAccountRepository users,EmployeeRequestRepository requests,WorkLogRepository logs,PayRateRepository rates,NotificationRepository notifications,PasswordEncoder encoder,ShiftPlanRepository plans,PlanLogService planLogs,RoomAssignmentRepository roomAssignments){this.users=users;this.requests=requests;this.logs=logs;this.rates=rates;this.notifications=notifications;this.encoder=encoder;this.plans=plans;this.planLogs=planLogs;this.roomAssignments=roomAssignments;}
 public List<EmployeePortalDtos.RequestView> requests(String username){return requests.findAllByEmployeeUsernameOrderByCreatedAtDesc(username).stream().map(EmployeePortalDtos.RequestView::from).toList();}
 public EmployeePortalDtos.RequestView create(String username,EmployeePortalDtos.CreateRequest r){UserAccount employee=user(username);if(r.endDate().isBefore(r.startDate()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Data finală trebuie să fie după data de început");EmployeeRequest request=requests.save(new EmployeeRequest(employee,employee.getHotel(),r.type(),r.startDate(),r.endDate(),r.message()));users.findAllByHotelIdAndActiveTrueOrderByUsername(employee.getHotel().getId()).stream().filter(account->account.getRole()==UserRole.MANAGER||account.getRole()==UserRole.EMPLOYER).forEach(manager->notifications.save(new Notification(manager,"Cerere nouă de la "+employee.getUsername(),r.type()+" · "+r.startDate(),"management")));return EmployeePortalDtos.RequestView.from(request);}
 public List<EmployeePortalDtos.RequestView> pending(String username){UserAccount manager=user(username);return requests.findAllByHotelIdAndStatusOrderByCreatedAtDesc(manager.getHotel().getId(),EmployeeRequestStatus.PENDING).stream().map(EmployeePortalDtos.RequestView::from).toList();}
 public EmployeePortalDtos.RequestView review(String username,Long id,EmployeePortalDtos.ReviewRequest r){UserAccount manager=user(username);EmployeeRequest request=requests.findById(id).filter(item->item.getEmployee().getHotel().getId().equals(manager.getHotel().getId())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(request.getStatus()!=EmployeeRequestStatus.PENDING)throw new ResponseStatusException(HttpStatus.CONFLICT,"Cererea a fost deja procesată");String response=r.response()==null?"":r.response();request.review(manager,r.approved(),response);if(r.approved())applyAbsence(request);notifications.save(new Notification(request.getEmployee(),r.approved()?"Cerere aprobată":"Cerere respinsă",response.isBlank()?"Cererea ta a fost procesată":response,r.approved()&&isAbsence(request)?"plan":"requests"));return EmployeePortalDtos.RequestView.from(request);}

 private void applyAbsence(EmployeeRequest request){if(!isAbsence(request))return;ShiftKind kind=request.getType()==EmployeeRequestType.VACATION?ShiftKind.VACATION:ShiftKind.SICK;for(LocalDate date=request.getStartDate();!date.isAfter(request.getEndDate());date=date.plusDays(1)){List<ShiftPlan> existing=plans.findAllByEmployeeIdAndWorkDate(request.getEmployee().getId(),date);ShiftPlan absence;if(existing.isEmpty()){absence=plans.save(new ShiftPlan(request.getEmployee(),request.getEmployee().getHotel(),null,date,null,null,"Cerere aprobată",kind));}else{absence=existing.get(0);absence.update(null,date,null,null,"Cerere aprobată",kind);planLogs.ensureFor(absence);for(int index=1;index<existing.size();index++){ShiftPlan extra=existing.get(index);extra.update(null,date,null,null,"Înlocuit de cererea aprobată",kind);planLogs.ensureFor(extra);plans.delete(extra);}}}}
 private boolean isAbsence(EmployeeRequest request){return request.getType()==EmployeeRequestType.VACATION||request.getType()==EmployeeRequestType.SICK;}
 public void profile(String username,EmployeePortalDtos.ProfileUpdate r){user(username).updateProfile(r.firstName(),r.lastName(),blank(r.email()),blank(r.phone()),r.address(),r.steuerClass());}
 public void password(String username,EmployeePortalDtos.PasswordChange r){UserAccount user=user(username);if(!encoder.matches(r.currentPassword(),user.getPassword()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Parola actuală nu este corectă");user.changePassword(encoder.encode(r.newPassword()));}
 @Transactional(readOnly=true) public List<ManagementDtos.RoomAssignmentView> rooms(String username,LocalDate from,LocalDate to){user(username);return roomAssignments.findAllByEmployeeUsernameAndWorkDateBetweenOrderByWorkDateAscRoomNumberAsc(username,from,to).stream().map(ManagementDtos.RoomAssignmentView::from).toList();}
 public ManagementDtos.RoomAssignmentView completeRoom(String username,Long id,EmployeePortalDtos.CompleteRoom r){UserAccount employee=user(username);RoomAssignment room=roomAssignments.findByIdAndEmployeeUsername(id,username).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if(room.getStatus()==RoomAssignmentStatus.RELEASED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Camera este deja eliberată");room.complete(r.notes());users.findAllByHotelIdAndActiveTrueOrderByUsername(employee.getHotel().getId()).stream().filter(account->account.getRole()==UserRole.CHECKER||account.getRole()==UserRole.MANAGER).forEach(checker->notifications.save(new Notification(checker,"Camera "+room.getRoomNumber()+" este gata",employee.getUsername()+" a marcat camera ca terminată","checker")));return ManagementDtos.RoomAssignmentView.from(room);}
 @Transactional(readOnly=true) public EmployeePortalDtos.PayrollYear payroll(String username,int year){UserAccount employee=user(username);List<WorkLog> yearLogs=logs.findAllByEmployeeUsernameAndWorkDateBetweenOrderByWorkDateDesc(username,LocalDate.of(year,1,1),LocalDate.of(year,12,31)).stream().filter(log->log.getStatus()==LogStatus.APPROVED).toList();List<EmployeePortalDtos.PayrollMonth> months=new ArrayList<>();for(int month=1;month<=12;month++){final int m=month;List<WorkLog> items=yearLogs.stream().filter(log->log.getWorkDate().getMonthValue()==m).toList();BigDecimal regular=sum(items),sunday=sum(items.stream().filter(log->log.getWorkDate().getDayOfWeek()==DayOfWeek.SUNDAY).toList()),night=items.stream().map(this::nightHours).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal base=items.stream().map(log->log.getCalculatedHours().multiply(rate(username,log.getWorkDate()))).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal sundayPay=items.stream().filter(log->log.getWorkDate().getDayOfWeek()==DayOfWeek.SUNDAY).map(log->log.getCalculatedHours().multiply(rate(username,log.getWorkDate())).multiply(employee.getHotel().getSundayPremiumPercent()).divide(BigDecimal.valueOf(100))).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal nightPay=night.multiply(rate(username,LocalDate.of(year,month,1))).multiply(employee.getHotel().getNightPremiumPercent()).divide(BigDecimal.valueOf(100));BigDecimal premiums=sundayPay.add(nightPay),gross=base.add(premiums);months.add(new EmployeePortalDtos.PayrollMonth(year,month,regular,sunday,night,base.setScale(2,RoundingMode.HALF_UP),premiums.setScale(2,RoundingMode.HALF_UP),gross.setScale(2,RoundingMode.HALF_UP),gross.multiply(netFactor(employee.getSteuerClass())).setScale(2,RoundingMode.HALF_UP)));}BigDecimal totalHours=months.stream().map(EmployeePortalDtos.PayrollMonth::regularHours).reduce(BigDecimal.ZERO,BigDecimal::add),totalGross=months.stream().map(EmployeePortalDtos.PayrollMonth::gross).reduce(BigDecimal.ZERO,BigDecimal::add),net=months.stream().map(EmployeePortalDtos.PayrollMonth::estimatedNet).reduce(BigDecimal.ZERO,BigDecimal::add);return new EmployeePortalDtos.PayrollYear(year,months,totalHours,totalGross,net);}
 private BigDecimal nightHours(WorkLog log){if(log.getStartTime()==null||log.getEndTime()==null)return BigDecimal.ZERO;LocalTime start=log.getStartTime(),end=log.getEndTime();long total=ChronoUnit.MINUTES.between(start,end);if(total<=0)total+=1440;long night=0;for(long minute=0;minute<total;minute++){LocalTime t=start.plusMinutes(minute);if(!t.isBefore(LocalTime.of(22,0))||t.isBefore(LocalTime.of(6,0)))night++;}return BigDecimal.valueOf(night).divide(BigDecimal.valueOf(60),2,RoundingMode.HALF_UP);}
 private BigDecimal sum(List<WorkLog> list){return list.stream().map(WorkLog::getCalculatedHours).reduce(BigDecimal.ZERO,BigDecimal::add);}private BigDecimal rate(String username,LocalDate date){return rates.findFirstByEmployeeUsernameAndEffectiveFromLessThanEqualOrderByEffectiveFromDesc(username,date).map(PayRate::getHourlyRate).orElse(user(username).getHourlyRate());}private BigDecimal netFactor(Integer steuer){return switch(steuer==null?1:steuer){case 3->new BigDecimal("0.78");case 5,6->new BigDecimal("0.62");case 2,4->new BigDecimal("0.70");default->new BigDecimal("0.68");};}private String blank(String value){return value==null||value.isBlank()?null:value.trim();}private UserAccount user(String username){return users.findByUsername(username).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED));}
}
