package com.ejacot.taskmanagement.hotel;

import com.ejacot.taskmanagement.user.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.time.*;
import java.util.*;

@Service @Transactional
public class ManagementService{
 private final UserAccountRepository users;private final ShiftPlanRepository plans;private final WorkLogRepository logs;private final WorkTypeRepository types;private final NotificationRepository notifications;private final PayRateRepository payRates;
 public ManagementService(UserAccountRepository users,ShiftPlanRepository plans,WorkLogRepository logs,WorkTypeRepository types,NotificationRepository notifications,PayRateRepository payRates){this.users=users;this.plans=plans;this.logs=logs;this.types=types;this.notifications=notifications;this.payRates=payRates;}
 @Transactional(readOnly=true) public ManagementDtos.Overview overview(String username){UserAccount manager=user(username);Long hotel=hotel(manager);LocalDate monday=LocalDate.now().minusDays(LocalDate.now().getDayOfWeek().getValue()-1L);return new ManagementDtos.Overview(users.findAllByHotelIdAndActiveTrueOrderByUsername(hotel).stream().map(u->new ManagementDtos.EmployeeView(u.getId(),u.getUsername(),displayName(u),u.getRole().name())).toList(),plans.findAllByHotelIdAndWorkDateBetweenOrderByWorkDateAscStartTimeAsc(hotel,monday,monday.plusDays(13)).stream().map(HotelDtos.PlanView::from).toList(),logs.findAllByHotelIdAndStatusOrderByWorkDateDesc(hotel,LogStatus.SUBMITTED).stream().map(HotelDtos.LogView::from).toList());}
 public List<HotelDtos.PlanView> createPlans(String username,ManagementDtos.PlanRequest r){UserAccount manager=user(username);Long hotel=hotel(manager);WorkType type=resolveType(hotel,r.workTypeId(),r.kind());List<UserAccount> employees=users.findAllById(r.employeeIds()).stream().filter(u->u.getHotel()!=null&&u.getHotel().getId().equals(hotel)).toList();if(employees.size()!=r.employeeIds().size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid employees");List<ShiftPlan> created=employees.stream().map(e->new ShiftPlan(e,manager.getHotel(),type,r.date(),r.startTime(),r.endTime(),r.notes(),r.kind())).toList();plans.saveAll(created);employees.forEach(e->notifications.save(new Notification(e,"Plan nou pentru "+r.date(),label(type,r.kind())+" "+times(r.startTime(),r.endTime()),"plan")));return created.stream().map(HotelDtos.PlanView::from).toList();}
 public HotelDtos.PlanView updatePlan(String username,Long id,ManagementDtos.UpdatePlanRequest r){UserAccount manager=user(username);ShiftPlan p=plans.findByIdAndHotelId(id,hotel(manager)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));WorkType type=resolveType(hotel(manager),r.workTypeId(),r.kind());p.update(type,r.date(),r.startTime(),r.endTime(),r.notes(),r.kind());notifications.save(new Notification(p.getEmployee(),"Plan modificat pentru "+r.date(),label(type,r.kind())+" "+times(r.startTime(),r.endTime()),"plan"));return HotelDtos.PlanView.from(p);}
 public HotelDtos.LogView review(String username,Long id,ManagementDtos.ReviewRequest r){UserAccount reviewer=user(username);WorkLog log=logs.findByIdAndHotelId(id,hotel(reviewer)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));log.review(reviewer,r.approved(),r.reason());notifications.save(new Notification(log.getEmployee(),r.approved()?"Activitate aprobată":"Activitate respinsă",r.approved()?"Înregistrarea din "+log.getWorkDate()+" a fost aprobată":r.reason(),"history"));return HotelDtos.LogView.from(log);}
 @Transactional(readOnly=true) public ManagementDtos.AttachmentView attachment(String username,Long id){UserAccount reviewer=user(username);WorkLog log=logs.findByIdAndHotelId(id,hotel(reviewer)).filter(WorkLog::hasAttachment).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));return new ManagementDtos.AttachmentView(log.getAttachmentName(),log.getAttachmentData());}
 public HotelDtos.WorkTypeView createType(String username,ManagementDtos.WorkTypeRequest r){UserAccount manager=user(username);WorkType type=types.save(new WorkType(manager.getHotel(),r.code().toUpperCase(),r.name(),r.unit(),r.roomsPerHour(),r.color()==null?"#246F60":r.color()));return HotelDtos.WorkTypeView.from(type);}
 public void addPayRate(String username,ManagementDtos.PayRateRequest r){UserAccount employer=user(username);if(employer.getRole()!=UserRole.EMPLOYER)throw new ResponseStatusException(HttpStatus.FORBIDDEN);UserAccount employee=users.findById(r.employeeId()).filter(u->u.getHotel()!=null&&u.getHotel().getId().equals(hotel(employer))).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));payRates.save(new PayRate(employee,r.hourlyRate(),r.effectiveFrom()));}
 private UserAccount user(String name){return users.findByUsername(name).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED));}private Long hotel(UserAccount u){if(u.getHotel()==null)throw new ResponseStatusException(HttpStatus.CONFLICT);return u.getHotel().getId();}
 private WorkType resolveType(Long hotel,Long id,ShiftKind kind){if(kind!=ShiftKind.WORK)return null;if(id==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Work type required");return types.findById(id).filter(t->t.getHotel().getId().equals(hotel)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private String displayName(UserAccount u){String name=java.util.stream.Stream.of(u.getFirstName(),u.getLastName()).filter(Objects::nonNull).collect(java.util.stream.Collectors.joining(" "));return name.isBlank()?u.getUsername():name;}
 private String label(WorkType t,ShiftKind k){return k==ShiftKind.WORK?t.getName():switch(k){case FREE->"Liber";case VACATION->"Concediu";case SICK->"Medical";default->"";};}private String times(LocalTime a,LocalTime b){return a==null?"":a+"–"+b;}
}
