package com.ejacot.taskmanagement.hotel;

import com.ejacot.taskmanagement.user.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;
import java.time.*;
import java.util.*;

@Service @Transactional
public class ManagementService{
 private final UserAccountRepository users;private final ShiftPlanRepository plans;private final WorkLogRepository logs;private final WorkTypeRepository types;private final NotificationRepository notifications;private final PayRateRepository payRates;private final PlanLogService planLogs;private final RoomAssignmentRepository roomAssignments;
 public ManagementService(UserAccountRepository users,ShiftPlanRepository plans,WorkLogRepository logs,WorkTypeRepository types,NotificationRepository notifications,PayRateRepository payRates,PlanLogService planLogs,RoomAssignmentRepository roomAssignments){this.users=users;this.plans=plans;this.logs=logs;this.types=types;this.notifications=notifications;this.payRates=payRates;this.planLogs=planLogs;this.roomAssignments=roomAssignments;}
 @Transactional(readOnly=true) public ManagementDtos.Overview overview(String username){UserAccount manager=user(username);Long hotel=hotel(manager);LocalDate monday=LocalDate.now().minusDays(LocalDate.now().getDayOfWeek().getValue()-1L);return new ManagementDtos.Overview(users.findAllByHotelIdAndActiveTrueOrderByUsername(hotel).stream().map(u->new ManagementDtos.EmployeeView(u.getId(),u.getUsername(),displayName(u),u.getRole().name())).toList(),plans.findAllByHotelIdAndWorkDateBetweenOrderByWorkDateAscStartTimeAsc(hotel,monday,monday.plusDays(13)).stream().map(HotelDtos.PlanView::from).toList(),logs.findAllByHotelIdAndStatusOrderByWorkDateDesc(hotel,LogStatus.SUBMITTED).stream().map(HotelDtos.LogView::from).toList());}
 public List<HotelDtos.PlanView> createPlans(String username,ManagementDtos.PlanRequest r){UserAccount manager=user(username);Long hotel=hotel(manager);WorkType type=resolveType(hotel,r.workTypeId(),r.kind());List<UserAccount> employees=users.findAllById(r.employeeIds()).stream().filter(u->u.getHotel()!=null&&u.getHotel().getId().equals(hotel)).toList();if(employees.size()!=r.employeeIds().size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid employees");List<ShiftPlan> created=employees.stream().map(e->new ShiftPlan(e,manager.getHotel(),type,r.date(),r.startTime(),r.endTime(),r.notes(),r.kind())).toList();plans.saveAll(created);created.forEach(planLogs::ensureFor);employees.forEach(e->notifications.save(new Notification(e,"Plan nou pentru "+r.date(),label(type,r.kind())+" "+times(r.startTime(),r.endTime()),"plan")));return created.stream().map(HotelDtos.PlanView::from).toList();}
 public HotelDtos.PlanView updatePlan(String username,Long id,ManagementDtos.UpdatePlanRequest r){UserAccount manager=user(username);ShiftPlan p=plans.findByIdAndHotelId(id,hotel(manager)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));WorkType type=resolveType(hotel(manager),r.workTypeId(),r.kind());p.update(type,r.date(),r.startTime(),r.endTime(),r.notes(),r.kind());planLogs.ensureFor(p);notifications.save(new Notification(p.getEmployee(),"Plan modificat pentru "+r.date(),label(type,r.kind())+" "+times(r.startTime(),r.endTime()),"plan"));return HotelDtos.PlanView.from(p);}
 @Transactional(readOnly=true) public List<HotelDtos.PlanView> plans(String username,LocalDate from,LocalDate to){UserAccount manager=user(username);if(to.isBefore(from)||to.isAfter(from.plusDays(62)))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Interval invalid");return plans.findAllByHotelIdAndWorkDateBetweenOrderByWorkDateAscStartTimeAsc(hotel(manager),from,to).stream().map(HotelDtos.PlanView::from).toList();}
 public List<HotelDtos.PlanView> copyWeek(String username,ManagementDtos.CopyWeekRequest r){UserAccount manager=user(username);if(!r.sourceMonday().getDayOfWeek().equals(DayOfWeek.MONDAY)||!r.targetMonday().getDayOfWeek().equals(DayOfWeek.MONDAY))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Săptămâna trebuie să înceapă luni");Long hotel=hotel(manager);List<ShiftPlan> source=plans.findAllByHotelIdAndWorkDateBetweenOrderByWorkDateAscStartTimeAsc(hotel,r.sourceMonday(),r.sourceMonday().plusDays(6));List<ShiftPlan> created=new ArrayList<>();for(ShiftPlan original:source){LocalDate target=original.getWorkDate().plusDays(java.time.temporal.ChronoUnit.DAYS.between(r.sourceMonday(),r.targetMonday()));List<ShiftPlan> existing=plans.findAllByEmployeeIdAndWorkDate(original.getEmployee().getId(),target);if(!existing.isEmpty()){if(!r.overwrite())continue;clear(existing,target);}ShiftPlan copy=plans.save(new ShiftPlan(original.getEmployee(),manager.getHotel(),original.getWorkType(),target,original.getStartTime(),original.getEndTime(),original.getNotes(),original.getKind()));planLogs.ensureFor(copy);created.add(copy);notifications.save(new Notification(original.getEmployee(),"Plan copiat pentru "+target,label(original.getWorkType(),original.getKind())+" "+times(original.getStartTime(),original.getEndTime()),"plan"));}return created.stream().map(HotelDtos.PlanView::from).toList();}
 private void clear(List<ShiftPlan> existing,LocalDate date){for(ShiftPlan old:existing){old.update(null,date,null,null,"Înlocuit prin copiere",ShiftKind.FREE);planLogs.ensureFor(old);plans.delete(old);}}
 @Transactional(readOnly=true) public List<ManagementDtos.RoomAssignmentView> rooms(String username,LocalDate from,LocalDate to){UserAccount manager=user(username);return roomAssignments.findAllByHotelIdAndWorkDateBetweenOrderByWorkDateAscRoomNumberAsc(hotel(manager),from,to).stream().map(ManagementDtos.RoomAssignmentView::from).toList();}
 public List<ManagementDtos.RoomAssignmentView> assignRooms(String username,ManagementDtos.RoomAssignmentRequest r){UserAccount manager=user(username);List<UserAccount> employees=users.findAllById(r.employeeIds()).stream().filter(value->value.getHotel()!=null&&value.getHotel().getId().equals(hotel(manager))).toList();if(employees.size()!=r.employeeIds().size())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Angajați invalizi");List<RoomAssignment> saved=new ArrayList<>();for(UserAccount employee:employees){roomAssignments.deleteAllByEmployeeIdAndWorkDate(employee.getId(),r.date());for(ManagementDtos.RoomInput room:r.rooms())saved.add(roomAssignments.save(new RoomAssignment(manager.getHotel(),employee,r.date(),room.number().trim(),room.category())));notifications.save(new Notification(employee,"Lista camerelor pentru "+r.date(),r.rooms().size()+" camere repartizate","plan"));}return saved.stream().map(ManagementDtos.RoomAssignmentView::from).toList();}
 public HotelDtos.LogView review(String username,Long id,ManagementDtos.ReviewRequest r){UserAccount reviewer=user(username);WorkLog log=logs.findByIdAndHotelId(id,hotel(reviewer)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));String reason=r.reason()==null||r.reason().isBlank()?"Modificarea nu a fost aprobată":r.reason();if(!r.approved()&&log.getShiftPlan()!=null)log.rejectCorrection(reviewer,reason,planLogs.plannedHours(log.getShiftPlan()),planLogs.breakMinutes(log.getShiftPlan()));else log.review(reviewer,r.approved(),reason);notifications.save(new Notification(log.getEmployee(),r.approved()?"Modificare aprobată":"Modificare respinsă",r.approved()?"Orele modificate din "+log.getWorkDate()+" au fost aprobate":reason,"history"));return HotelDtos.LogView.from(log);}
 @Transactional(readOnly=true) public ManagementDtos.AttachmentView attachment(String username,Long id){UserAccount reviewer=user(username);WorkLog log=logs.findByIdAndHotelId(id,hotel(reviewer)).filter(WorkLog::hasAttachment).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));return new ManagementDtos.AttachmentView(log.getAttachmentName(),log.getAttachmentData());}
 public HotelDtos.WorkTypeView createType(String username,ManagementDtos.WorkTypeRequest r){UserAccount manager=user(username);WorkType type=types.save(new WorkType(manager.getHotel(),r.code().toUpperCase(),r.name(),r.unit(),r.roomsPerHour(),r.color()==null?"#246F60":r.color()));return HotelDtos.WorkTypeView.from(type);}
 public void addPayRate(String username,ManagementDtos.PayRateRequest r){UserAccount employer=user(username);if(employer.getRole()!=UserRole.EMPLOYER)throw new ResponseStatusException(HttpStatus.FORBIDDEN);UserAccount employee=users.findById(r.employeeId()).filter(u->u.getHotel()!=null&&u.getHotel().getId().equals(hotel(employer))).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));payRates.save(new PayRate(employee,r.hourlyRate(),r.effectiveFrom()));}
 private UserAccount user(String name){return users.findByUsername(name).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED));}private Long hotel(UserAccount u){if(u.getHotel()==null)throw new ResponseStatusException(HttpStatus.CONFLICT);return u.getHotel().getId();}
 private WorkType resolveType(Long hotel,Long id,ShiftKind kind){if(kind!=ShiftKind.WORK)return null;if(id==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Work type required");return types.findById(id).filter(t->t.getHotel().getId().equals(hotel)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 private String displayName(UserAccount u){String name=java.util.stream.Stream.of(u.getFirstName(),u.getLastName()).filter(Objects::nonNull).collect(java.util.stream.Collectors.joining(" "));return name.isBlank()?u.getUsername():name;}
 private String label(WorkType t,ShiftKind k){return k==ShiftKind.WORK?t.getName():switch(k){case FREE->"Liber";case VACATION->"Concediu";case SICK->"Medical";default->"";};}private String times(LocalTime a,LocalTime b){return a==null?"":a+"–"+b;}
}
