ALTER TABLE app_users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMP WITH TIME ZONE;

ALTER TABLE room_assignments ADD COLUMN IF NOT EXISTS defect_status VARCHAR(30);
ALTER TABLE room_assignments ADD COLUMN IF NOT EXISTS defect_resolved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE room_assignments ADD COLUMN IF NOT EXISTS defect_resolved_by BIGINT REFERENCES app_users(id);
ALTER TABLE room_assignments ADD COLUMN IF NOT EXISTS defect_photo_name VARCHAR(255);
ALTER TABLE room_assignments ADD COLUMN IF NOT EXISTS defect_photo_data TEXT;

CREATE TABLE IF NOT EXISTS outbound_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient VARCHAR(255) NOT NULL,
    channel VARCHAR(30) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbound_messages_status ON outbound_messages(status, created_at);
