CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
    first_name VARCHAR(80),
    last_name VARCHAR(80),
    default_hourly_rate NUMERIC(10,2) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    default_break_minutes INT NOT NULL DEFAULT 30,
    language VARCHAR(10) NOT NULL DEFAULT 'ro'
);

INSERT INTO user_profiles (user_id, first_name, last_name, default_hourly_rate, currency, default_break_minutes, language)
SELECT u.id,
       u.first_name,
       u.last_name,
       COALESCE(u.hourly_rate, 0),
       'EUR',
       30,
       'ro'
FROM app_users u
WHERE NOT EXISTS (
    SELECT 1 FROM user_profiles p WHERE p.user_id = u.id
);

ALTER TABLE work_types ADD COLUMN IF NOT EXISTS owner_id BIGINT REFERENCES app_users(id);
ALTER TABLE work_types ADD COLUMN IF NOT EXISTS custom_hourly_rate NUMERIC(10,2);
ALTER TABLE work_types ALTER COLUMN hotel_id DROP NOT NULL;
ALTER TABLE work_logs ALTER COLUMN hotel_id DROP NOT NULL;
ALTER TABLE work_logs ADD COLUMN IF NOT EXISTS hourly_rate_snapshot NUMERIC(10,2);
ALTER TABLE work_logs ADD COLUMN IF NOT EXISTS gross_amount NUMERIC(10,2);
