ALTER TABLE outbound_messages ADD COLUMN IF NOT EXISTS sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE outbound_messages ADD COLUMN IF NOT EXISTS failed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE outbound_messages ADD COLUMN IF NOT EXISTS error_message VARCHAR(500);
