CREATE TABLE room_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id BIGINT NOT NULL REFERENCES hotels(id),
    employee_id BIGINT NOT NULL REFERENCES app_users(id),
    work_date DATE NOT NULL,
    room_number VARCHAR(20) NOT NULL,
    category VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_room_assignments_employee_date ON room_assignments(employee_id, work_date);
CREATE INDEX idx_room_assignments_hotel_date ON room_assignments(hotel_id, work_date);
